# Roughly based on
# https://github.com/flameshot-org/flameshot/blob/master/.github/workflows/build_cmake.yml
# https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
# https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: Test program building(CMake)

on: [push, pull_request]

#env:
  #TBD

jobs:
  linux-build:
    name: ${{ matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-22.04]
        cpp_compiler: [g++, clang++]

    steps:
      - name: Checkout source code
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Checkout source code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install \
            cmake \
            extra-cmake-modules \
            build-essential \
            libglpk-dev \
            libconfig++-dev \
            libeigen3-dev \
            libboost-container-dev

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        # Not sure why this is needed?? 
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -S ${{ github.workspace }}

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }}
