# Roughly based on
# https://github.com/flameshot-org/flameshot/blob/master/.github/workflows/build_cmake.yml
# https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
# https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: CMake build of Quadelect

on: [push, pull_request]

#env:
  #TBD

jobs:
  linux-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-22.04, windows-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        include:
          - os: ubuntu-22.04
            cpp_compiler: g++
          - os: ubuntu-22.04
            cpp_compiler: clang++
          - os: windows-latest
            cpp_compiler: cl
        exclude:
          - os: ubuntu-22.04
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++

    name: ${{ matrix.os }}, ${{ matrix.cpp_compiler }}

    steps:
      - name: Checkout source code
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Checkout source code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install \
            cmake \
            extra-cmake-modules \
            build-essential \
            libglpk-dev \
            libconfig++-dev \
            libeigen3-dev \
            libboost-container-dev

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        # Not sure why this is needed?? 
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }}
